#!/usr/bin/env bash
#
# backfill-vidiff-statuses.sh
#
# Post the `CI / VIDiff (<platform>)` commit status for every push-<sha> VIDiff
# report already deployed under gh-pages `vidiff/`, so the CI Dashboard (whose
# badges are sourced from commit statuses) reflects diff reports that were
# generated by the VIDiff backfill but never had a status posted.
#
# This does NOT run LabVIEW or regenerate any report — it only reads the deployed
# report list and posts statuses that point at those existing reports. Safe and
# idempotent: re-posting an identical status is a no-op for the dashboard, which
# de-duplicates to the latest status per context.
#
# Usage:
#   GH_TOKEN=... ./backfill-vidiff-statuses.sh [--repo owner/name] [--dry-run]
#                                              [--only-missing] [--pages-url URL]
#
# Defaults: repo from `gh repo view`, live posting, only-missing OFF (re-asserts
# all), pages URL from the repo's configured Pages site.

set -euo pipefail

REPO=""
DRY_RUN=0
ONLY_MISSING=0
PAGES_URL=""   # default: derived from the repo's Pages site after REPO is resolved

while [ $# -gt 0 ]; do
  case "$1" in
    --repo)         REPO="$2"; shift 2 ;;
    --dry-run)      DRY_RUN=1; shift ;;
    --only-missing) ONLY_MISSING=1; shift ;;
    --pages-url)    PAGES_URL="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$REPO" ]; then
  REPO=$(gh repo view --json nameWithOwner --jq '.nameWithOwner')
fi

# Repo-agnostic default: derive the Pages site (owner.github.io/repo) from the
# resolved repo when not given via --pages-url. Owner is lowercased for the host.
if [ -z "$PAGES_URL" ]; then
  _owner=$(printf '%s' "${REPO%%/*}" | tr '[:upper:]' '[:lower:]')
  PAGES_URL="https://${_owner}.github.io/${REPO##*/}"
fi

echo "Repo:        $REPO"
echo "Pages URL:   $PAGES_URL"
echo "Dry run:     $DRY_RUN"
echo "Only missing:$ONLY_MISSING"
echo ""

# 1) List deployed VIDiff reports on gh-pages: vidiff/push-<sha>/<platform>/vidiff/changes.json
# (read into an array without mapfile, which is unavailable on bash 3.2/macOS)
REPORTS=()
while IFS= read -r line; do
  [ -n "$line" ] && REPORTS+=("$line")
done < <(
  gh api "repos/$REPO/git/trees/gh-pages?recursive=1" \
    --jq '.tree[].path | select(test("^vidiff/push-[0-9a-f]+/(windows|linux)/vidiff/changes\\.json$"))'
)
echo "Deployed VIDiff reports found: ${#REPORTS[@]}"

POSTED=0
SKIPPED=0
for path in "${REPORTS[@]}"; do
  # path = vidiff/push-<sha>/<platform>/vidiff/changes.json
  sha=$(echo "$path" | sed -E 's#^vidiff/push-([0-9a-f]+)/.*#\1#')
  platform=$(echo "$path" | sed -E 's#^vidiff/push-[0-9a-f]+/([a-z]+)/.*#\1#')
  context="CI / VIDiff (${platform})"

  # The dashboard's VIDiff badge opens the unified VI Browser filtered to this
  # commit's changed VIs (matching vidiff-deploy.yml for pushes).
  target="${PAGES_URL}/vi-snapshots/index.html?sha=${sha}&changed=1"

  if [ "$ONLY_MISSING" = "1" ]; then
    existing=$(gh api "repos/$REPO/commits/$sha/statuses" \
      --jq "[.[] | select(.context==\"$context\")] | length" 2>/dev/null || echo 0)
    if [ "${existing:-0}" -gt 0 ]; then
      SKIPPED=$((SKIPPED+1))
      continue
    fi
  fi

  echo "  ${sha:0:9}  ${context}"
  if [ "$DRY_RUN" = "0" ]; then
    gh api -X POST "repos/$REPO/statuses/$sha" \
      -f state="success" \
      -f context="$context" \
      -f description="VIDiff (${platform}) success" \
      -f target_url="$target" >/dev/null
  fi
  POSTED=$((POSTED+1))
done

echo ""
echo "=== Done: ${POSTED} status(es) $([ "$DRY_RUN" = "1" ] && echo 'would be posted' || echo 'posted'), ${SKIPPED} already present ==="
