#!/usr/bin/env python3
"""
build-tooling-vipc.py - Generate `ci-tooling.vipc` from `ci-tooling.packages.json`.

The CI worker image bakes in a default set of third-party LabVIEW tooling
(Antidoc, Caraya, VI Tester, ...). Producing a real VI Package Configuration
normally requires the VIPM GUI (Windows-only), which is awkward for a
cross-platform, version-controlled, portable setup. This script instead emits a
VIPM-compatible `.vipc` directly from a plain JSON manifest, so the tooling set
is a one-line edit + regenerate in any repo.

Output format (verified against this repo's real `COTC Dependencies.vipc`):
  A `.vipc` is a ZIP archive whose `config.xml` lists each package as
    <Package><Name>name-version</Name><Included>false</Included>
            <Dependency>false</Dependency><Pinned>false</Pinned></Package>
  `Included=false` means the package binary is NOT bundled; `vipm apply_vipc`
  downloads it (and its dependencies) from the configured VIPM repository at
  apply time -- exactly how `COTC Dependencies.vipc` already works in this
  pipeline. We therefore emit config.xml only (no per-package .spec/.bmp, which
  only VIPM itself can produce); dependency resolution is left to VIPM.

The archive is written deterministically (stable entry order, fixed ZIP
timestamp, content-derived ID) so regenerating the same manifest yields
byte-identical output -- important because the image-build workflow hashes this
file into the immutable worker version.

Usage:
  python3 build-tooling-vipc.py [--manifest PATH] [--out PATH] [--labview-version YEAR]

Stdlib only; runs anywhere (macOS/Linux/Windows), no LabVIEW or VIPM required.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape

HERE = Path(__file__).resolve().parent
DEFAULT_MANIFEST = HERE / "ci-tooling.packages.json"
DEFAULT_OUT = HERE / "ci-tooling.vipc"

# Fixed ZIP member timestamp (the DOS epoch) keeps the archive byte-stable across
# regenerations regardless of when/where it runs.
_FIXED_ZIP_DATETIME = (1980, 1, 1, 0, 0, 0)
# Fixed config timestamps for the same reason; these fields are informational
# (apply is driven by `-labview_version` on the CLI), so a constant is fine.
_FIXED_CONFIG_DATE = "2026-01-01 00:00:00"


def labview_target_version(year: str) -> str:
    """
    Map a LabVIEW year to the .vipc Target <Version> string, e.g. 2026 ->
    '26.1 (64-bit)'. The CI base image is 64-bit LabVIEW; the minor '.1' matches
    the 26.1 NI feed the image installs from. Falls back to '<yy>.1 (64-bit)'.
    """
    try:
        major = int(year) - 2000
    except (TypeError, ValueError):
        return "26.1 (64-bit)"
    return f"{major}.1 (64-bit)"


def selected_packages(manifest: dict) -> list[dict]:
    """Return the manifest packages flagged for inclusion, in manifest order."""
    pkgs = (manifest.get("vipmPackages") or {}).get("packages") or []
    out: list[dict] = []
    for p in pkgs:
        if not isinstance(p, dict):
            continue
        if p.get("include") is False:
            continue
        name = (p.get("name") or "").strip()
        if name:
            out.append(p)
    return out


def package_id(packages: list[dict]) -> str:
    """Deterministic 32-hex config ID derived from the included package specs."""
    basis = "\n".join(qualified_name(p) for p in packages)
    return hashlib.md5(basis.encode("utf-8")).hexdigest()


def qualified_name(pkg: dict) -> str:
    """'name-version' when a version is pinned, else bare 'name' (latest)."""
    name = pkg["name"].strip()
    version = pkg.get("version")
    version = str(version).strip() if version not in (None, "") else ""
    return f"{name}-{version}" if version else name


def build_config_xml(manifest: dict, packages: list[dict], labview_version: str) -> str:
    target = manifest.get("target") or {}
    target_name = escape(str(target.get("name") or "LabVIEW"))
    target_version = escape(labview_target_version(labview_version))
    config_id = package_id(packages)

    lines = [
        f'<VI_Package_Configuration File_Type="xml" Version="0.6" '
        f'Created_Date="{_FIXED_CONFIG_DATE}" Modified_Date="{_FIXED_CONFIG_DATE}" '
        f'Creator="cotc-ci" Comments="Generated by build-tooling-vipc.py from '
        f'ci-tooling.packages.json" ID="{config_id}">',
        "  <Target>",
        f"    <Name>{target_name}</Name>",
        f"    <Version>{target_version}</Version>",
    ]
    for pkg in packages:
        lines += [
            "    <Package>",
            f"      <Name>{escape(qualified_name(pkg))}</Name>",
            "      <Included>false</Included>",
            "      <Dependency>false</Dependency>",
            "      <Pinned>false</Pinned>",
            "    </Package>",
        ]
    lines += ["  </Target>", "</VI_Package_Configuration>", ""]
    return "\n".join(lines)


def write_vipc(out_path: Path, config_xml: str) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    info = zipfile.ZipInfo("config.xml", date_time=_FIXED_ZIP_DATETIME)
    info.compress_type = zipfile.ZIP_DEFLATED
    info.external_attr = 0o600 << 16
    with zipfile.ZipFile(out_path, "w") as z:
        z.writestr(info, config_xml.encode("utf-8"))


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Generate ci-tooling.vipc from the package manifest.")
    ap.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--labview-version", default=None,
                    help="Override the LabVIEW year (default: manifest target.labviewVersion).")
    args = ap.parse_args(argv)

    if not args.manifest.exists():
        print(f"ERROR: manifest not found: {args.manifest}", file=sys.stderr)
        return 1

    try:
        manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"ERROR: manifest is not valid JSON: {exc}", file=sys.stderr)
        return 1

    labview_version = args.labview_version or str(
        (manifest.get("target") or {}).get("labviewVersion") or "2026"
    )
    packages = selected_packages(manifest)
    if not packages:
        print("ERROR: no included packages in manifest; nothing to generate.", file=sys.stderr)
        return 1

    config_xml = build_config_xml(manifest, packages, labview_version)
    write_vipc(args.out, config_xml)

    print(f"Wrote {args.out} (LabVIEW {labview_version}, {len(packages)} package(s)):")
    for pkg in packages:
        print(f"  - {qualified_name(pkg)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
